(defun ly:perl-configure-func ()
  (perl-completion-mode t)
  ;; (add-to-list 'ac-sources 'ac-source-perl-completion)
  (setq ac-sources '(ac-source-perl-completion)))
(setq plcmp-use-keymap nil)
(require 'perl-completion)
(defalias 'perl-mode 'cperl-mode)
(add-hook 'perl-mode-hook 'ly:perl-configure-func)
(add-hook 'cperl-mode-hook 'ly:perl-configure-func)
(add-to-list 'ac-source-perl-completion '(symbol . "P"))
(setq cperl-indent-level 4)
(setq plcmp-default-lighter " PLC")
